INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (1, 'searchInput', 1, 1);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (2, 'searchButton', 2, 1);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (3, 'firstHeading', 3, 1);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (4, 'Happiness', 4, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (5, 'Java', 5, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (6, 'context var 1', 6, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (7, 'context var 2', 7, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (8, 'context var 3', 8, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (9, 'context var 4', 9, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (10, 'context var 5', 10, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (11, 'context var 6', 11, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (12, 'context var 7', 12, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (13, 'context var 8', 13, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (14, 'context var 9', 14, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (16, 'context var 10', 15, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (17, 'Coronavirus', 33, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (18, 'Sleep', 34, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (19, 'Netcracker Technology', 35, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (20, 'Fail', 36, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (22, 'ybar-sbq', 38, 6);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (23, '//*[@id="ybar-sf"]/input[2]', 39, 6);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (24, 'search-input', 42, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (25, '//*[@id="header"]/div[3]/div/div/div[3]/form/button[3]', 44, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (26, '//*[@id="__layout"]/div/section/div[1]/div[2]/div[2]/div[1]/div[2]/div/div[1]/div/div/div[1]/div[5]/div/div[2]/span', 45, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (27, '//*[@id="__layout"]/div/section/div[1]/div[2]/div[2]/div[1]/div[2]/div/div[1]/div/div/div[1]/div[1]/a/span', 46, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (28, '//*[@id="buy-block"]/div[3]/div[1]/div/div[2]/span/span', 47, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (29, '//*[@id="buy-block"]/div[3]/div[1]/button', 48, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (31, 'Apple MacBook Pro', 63, 8);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (32, '//*[@id="__layout"]/div/div[2]/div/div[2]/div/div/div/div[2]/div[2]/a', 67, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (33, '/html/body/div[1]/div[2]/section/div/div[2]/div[3]/div/div[2]/div[7]/div/div/div[3]/span/span[1]', 69, 7);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (34, 'OnePlus 8T', 74, 8);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (35, 'Apple iPhone 12', 77, 8);