INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (4, 'wiki test string 1');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (5, 'wiki test string 2');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (6, 'context var 1');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (7, 'context var 2');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (8, 'context var 3');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (9, 'context var 4');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (10, 'context var 5');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (11, 'context var 6');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (12, 'context var 7');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (13, 'context var 8');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (14, 'context var 9');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (15, 'context var 10');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (2, 'wiki search button id');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (1, 'wiki search field id');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (3, 'wiki search result heading id');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (33, 'wiki test string 3');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (34, 'wiki test string 4');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (35, 'wiki test string 5');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (36, 'wiki test string 6');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (38, 'yahoo search field id');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (39, 'yahoo search button Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (44, 'Citrus search button Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (42, 'citrus search field id');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (49, 'citrus product price on cart Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (63, 'citrus product name 1');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (47, 'citrus product price on product page Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (46, 'citrus first product link Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (45, 'citrus first product price Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (69, 'citrus product price in order Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (67, 'citrus buy button on cart popup Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (48, 'citrus buy button on product page Xpath');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (74, 'citrus product name 2');
INSERT INTO public.parameter_key (parameter_key_id, key) VALUES (77, 'citrus product name 3');