package com.nc.project.model.util;

public enum ActionType {
    CLICK,
    SEND_KEYS,
    SWITCH_TAB,
    COMPARE_WITH_STRING,
    COMPARE_WITH_CONTEXT_VALUE,
    SCROLL_PAGE_TO_END,
    SAVE_ELEMENT_TEXT_TO_CONTEXT,
    SAVE_ELEMENT_ATTRIBUTE_TO_CONTEXT,
    FIND_ELEMENT_BY_ID,
    FIND_ELEMENT_BY_XPATH,
    FIND_ELEMENT_BY_CLASS_NAME,
    FIND_ELEMENT_BY_TAG_NAME,
    FIND_ELEMENT_BY_NAME,
    FIND_ELEMENT_BY_PARTIAL_LINK_TEXT,
    FIND_ELEMENT_BY_LINK_TEXT,
    FIND_ELEMENT_BY_CSS_SELECTOR,
    COMPOUND
}
