INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (1, 'searchInput', 1, 1);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (2, 'searchButton', 2, 1);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (3, 'firstHeading', 3, 1);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (4, 'Happiness', 4, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (5, 'Java', 5, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (6, 'context var 1', 6, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (7, 'context var 2', 7, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (8, 'context var 3', 8, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (9, 'context var 4', 9, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (10, 'context var 5', 10, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (11, 'context var 6', 11, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (12, 'context var 7', 12, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (13, 'context var 8', 13, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (14, 'context var 9', 14, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (16, 'context var 10', 15, 3);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (17, 'Coronavirus', 33, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (18, 'Sleep', 34, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (19, 'Netcracker Technology', 35, 2);
INSERT INTO public.parameter (parameter_id, value, parameter_key_id, data_set_id) VALUES (20, 'Fail', 36, 2);